### PR TITLE
added PATCH for updates

### PR DESCRIPTION
**Pull request by bkimminich**
- PATCH handled similar to PUT requests
- switched to SQLite for test suite (no prior DB setup needed, just clone repo, run ```npm install``` followed by ```npm test``` and all should work out of the box)
- added test DB file and IntelliJ-project files/folders to .gitignore

### CODE REVIEW

**Comment by sdepold** [comment]
Thanks a lot :)

**Comment by sdepold** [comment]
Can you please remove the 0.8 build from the travis.yml ?

**Comment by bkimminich** [comment]
I removed 0.8 and added 0.11. If that works then fine, if not I'll remove it again.

**Comment by sdepold** [comment]
Cool :) Thanks

**Comment by sdepold** [comment]
Just deployed this to 0.4.0

**Pull request merged**
